# Generated by Django 3.0.3 on 2021-08-31 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_in_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='in_progress',
        ),
    ]
